name: weatherapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  
  get: 4.6.5
  intl: ^0.17.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  
  syncfusion_flutter_charts: ^20.2.39

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
assets:
  - assets/images/cloud-in-blue-sky.jpg
  - assets/images/icon-01.jpg
